
#ifndef __INC_qas_config_hpp__
#define __INC_qas_config_hpp__

#define PACKAGE_NAME "${PACKAGE_NAME}"
#define PACKAGE_TITLE "${PACKAGE_TITLE}"
#define PACKAGE_VERSION "${PACKAGE_VERSION}"

#define PROGRAM_NAME "${PROGRAM_NAME}"
#define PROGRAM_TITLE "${PROGRAM_TITLE}"
#define VERSION "${VERSION}"
#define L10N_PREFIX "${L10N_PREFIX}"

#define SINGLE_APPLICATION_KEY "${PROGRAM_NAME}-${VERSION}"

#define INSTALL_DIR_DATA "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_DATA}"
#define INSTALL_DIR_L10N "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_L10N}"
#define INSTALL_DIR_APP_ICONS "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_APP_ICONS}"
#define INSTALL_DIR_WIDGETS_GRAPHICS "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_WIDGETS_GRAPHICS}"

#define INSTALL_DIR_ICONS_PNG_16 "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_ICONS_PNG_16}"
#define INSTALL_DIR_ICONS_PNG_32 "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_ICONS_PNG_32}"
#define INSTALL_DIR_ICONS_PNG_48 "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_ICONS_PNG_48}"
#define INSTALL_DIR_ICONS_PNG_64 "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_ICONS_PNG_64}"
#define INSTALL_DIR_ICONS_SVG "${CMAKE_INSTALL_PREFIX}/${INSTALL_DIR_ICONS_SVG}"

#endif
